# Test playbook
---
- hosts: all
  become: true
  vars:
    NS: TRAVIS
  pre_tasks:
    - name: Set NS fact and prometheus netdata hosts
      set_fact:
        namespace: "{{ NS }}"
        prometheus_monitored_hosts: [ 'node1' ]
        prometheus_admin_host: 'node1'
        prometheus_provision_only: true
    - name: Seed directory for NS
      file:
        path: "/etc/oio/sds/{{ NS }}"
        state: directory
    - name: Seed inventory on nodes
      copy:
        src: inventory.yml
        dest: "/etc/oio/sds/{{ NS }}/inventory.yml"
  roles:
    - role: users
    - role: repo
      openio_repository_no_log: false
      openio_repository_mirror_host: mirror2.openio.io
    - role: role_under_test
...
